name: CORY
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # 基本パッケージ
  - python=3.10.14
  - numpy=1.26.4
  - pyyaml=6.0.1
  - sqlite=3.45.3
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip=24.0

  # PyTorch/CUDA
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - torchvision=0.17.2
  - torchaudio=2.2.2

  # Windows 向けビルド済 deepspeed


  # pip インストール（deepspeed は conda-forge で入れるので削除）
  - pip:
    - absl-py==2.1.0
    - accelerate==0.31.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.43.3
    - bs4==0.0.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - datasets==2.20.0
    - dill==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - evaluate==0.4.2
    - exceptiongroup==1.2.1
    - filelock==3.14.0
    - fonttools==4.53.0
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h11==0.14.0
    - hf-transfer==0.1.6
    - hjson==3.1.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.24.3
    - inquirerpy==0.3.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.1
    - mdurl==0.1.2
    - multidict==6.0.5
    - multiprocess==0.70.16
    - ninja==1.11.1.1
    - nltk==3.8.1
    - openai==1.35.7
    - packaging==24.1
    - pandas==2.2.2
    - peft==0.12.0
    - pfzy==0.3.4
    - pillow==10.4.0
    - platformdirs==4.2.2
    - prompt-toolkit==3.0.47
    - protobuf==5.27.2
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - rouge-score==0.1.2
    - safetensors==0.4.3
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.7.1
    - setproctitle==1.3.3
    - shtab==1.7.1
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - sympy==1.12.1
    - tokenizers==0.19.1
    - torch-ema==0.3
    - tqdm==4.66.4
    - transformers==4.43.3
    - tree-sitter==0.22.3
    - typing-extensions==4.12.2
    - tyro==0.8.5
    - tzdata==2024.1
    - urllib3==2.2.1
    - wandb==0.17.3
    - wcwidth==0.2.13
    - xxhash==3.4.1
    - yarl==1.9.4
